"""
Notes
Ranges are in euclidian distance
"""

# Gameboard constants
BOARD_WIDTH = 40
BOARD_HEIGHT = 40
MIN_ELEVATION = -20
MAX_ELEVATION = 20

# Navigation constants
MOVEMENT_SPEED = 2

# HQ Constants
HQ_HEALTH = 250
HQ_COOLDOWN_REDUCTION = 1
RED_HQ_LOCATION = (5, 5)
BLUE_HQ_LOCATION = (35, 35)
HQ_SENSE_RANGE = 36
SPAWN_RADIUS = 2
TANK_SPAWN_COOLDOWN = 3
GUNNER_SPAWN_COOLDOWN = 2
HQ_HEALTH = 200

# Tank constants
TANK_HEALTH = 45
TANK_DAMAGE = 5
TANK_ATTACK_RANGE = 2
TANK_MOVEMENT_SPEED = 2
TANK_SENSE_RANGE = 25

# Gunner Constants
GUNNER_HEALTH = 10
GUNNER_DAMAGE = 10
GUNNER_ATTACK_RANGE = 15
GUNNER_MOVEMENT_SPEED = 2
GUNNER_SENSE_RANGE = 36


# Blockchain constants
