"""
Notes
Ranges are in euclidian distance
"""

# Gameboard constants
BOARD_WIDTH = 50
BOARD_HEIGHT = 50
MIN_ELEVATION = -20
MAX_ELEVATION = 20

# Navigation constants
MOVEMENT_SPEED = 1

# HQ Constants
HQ_HEALTH = 250
HQ_COOLDOWN_REDUCTION = 1
BLUE_HQ_LOCATION = (5, 5)
RED_HQ_LOCATION = (45, 45)
HQ_SENSE_RADIUS = 6

# Tank constants
TANK_HEALTH = 30
TANK_DAMAGE = 5
TANK_RANGE = 2
TANK_COOLDOWN = 3
TANK_MOVEMENT_SPEED = 1
TANK_SENSE_RADIUS = 5

# Gunner Constants
GUNNER_HEALTH = 10
GUNNER_DAMAGE = 10
GUNNER_RANGE = 5
GUNNER_COOLDOWN = 2
GUNNER_MOVEMENT_SPEED = 1
HQ_SENSE_RADIUS = 5


# Blockchain constants
