# Generated by Django 3.0.5 on 2020-06-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='blue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red', to='teams.Team'),
        ),
    ]
