# Generated by Django 3.0.5 on 2020-07-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
