# Generated by Django 3.0.5 on 2020-06-15 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('games', '0002_auto_20200611_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='blue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue', to='games.Submission'),
        ),
        migrations.AlterField(
            model_name='game',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red', to='games.Submission'),
        ),
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_team', to='teams.Team')),
                ('opp_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opp_team', to='teams.Team')),
            ],
        ),
    ]
