# Generated by Django 3.0.5 on 2020-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamerequest_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
    ]
