# Generated by Django 3.0.5 on 2020-05-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='outcome',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='teams.Submission'),
        ),
    ]
