# Generated by Django 3.0.8 on 2020-07-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='elo',
            field=models.IntegerField(default=1200),
        ),
    ]
