# Generated by Django 3.0.5 on 2020-07-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200721_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='display_elo',
            field=models.IntegerField(default=1200),
        ),
    ]
